// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeDHfo-ke5iBRsAb763szkq74QCjQwl-s',
    appId: '1:226288365106:web:2842e714482e65e49b962b',
    messagingSenderId: '226288365106',
    projectId: 'flutterfire-a3c22',
    authDomain: 'flutterfire-a3c22.firebaseapp.com',
    storageBucket: 'flutterfire-a3c22.appspot.com',
    measurementId: 'G-0Z8SKT6KTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE9xLUwFlI_ZMX2NhF9HV9iosaP-YDwTI',
    appId: '1:226288365106:android:7f870afd785061369b962b',
    messagingSenderId: '226288365106',
    projectId: 'flutterfire-a3c22',
    storageBucket: 'flutterfire-a3c22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB58-A-mPTnlMVVEx4Vjett9zYz83PgG6I',
    appId: '1:226288365106:ios:fc6df225e72c1b059b962b',
    messagingSenderId: '226288365106',
    projectId: 'flutterfire-a3c22',
    storageBucket: 'flutterfire-a3c22.appspot.com',
    androidClientId: '226288365106-4m5eqgld62lsojbue134t2eo4ntm2i84.apps.googleusercontent.com',
    iosClientId: '226288365106-1nudrgt5v276r6rnncakevamfc6v4gmq.apps.googleusercontent.com',
    iosBundleId: 'com.example.backend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB58-A-mPTnlMVVEx4Vjett9zYz83PgG6I',
    appId: '1:226288365106:ios:4e95c8567284d1429b962b',
    messagingSenderId: '226288365106',
    projectId: 'flutterfire-a3c22',
    storageBucket: 'flutterfire-a3c22.appspot.com',
    androidClientId: '226288365106-4m5eqgld62lsojbue134t2eo4ntm2i84.apps.googleusercontent.com',
    iosClientId: '226288365106-t74lbeieda1r2qn307434spgl3da85bu.apps.googleusercontent.com',
    iosBundleId: 'com.example.backend.RunnerTests',
  );
}
